# Generated by Django 3.1 on 2020-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitronese_word', models.CharField(max_length=30)),
                ('spanish_word', models.CharField(max_length=30)),
                ('word_class', models.CharField(choices=[('AFFIX', 'AFFIX'), ('NOUN', 'NOUN'), ('PROVERB', 'PROVERB'), ('POSTPOSITION', 'POSTPOSITION'), ('VERB', 'VERB'), ('ADJECTIVE', 'ADJECTIVE'), ('ARTICLE', 'ARTICLE'), ('PRONOUN', 'PRONOUN'), ('PREPOSITION', 'PREPOSITION'), ('ADVERB', 'ADVERB'), ('INTERJECTION', 'INTERJECTION'), ('CONJUNCTION', 'CONJUNCTION')], max_length=15)),
                ('orig_language', models.ManyToManyField(to='dictionary.OriginLanguage')),
            ],
        ),
    ]
