# Generated by Django 3.1 on 2020-08-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='spanish_word',
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='mitronese_word',
            field=models.CharField(max_length=40),
        ),
    ]
