# Generated by Django 3.1 on 2020-08-08 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_mitron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='organo_convocante',
            new_name='manager_agency',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='procedure',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
