# Generated by Django 3.1 on 2020-08-08 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_mitron', '0002_auto_20200808_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='COIIItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coii_number', models.CharField(max_length=9, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)], verbose_name='COII number')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_mitron.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_number', models.IntegerField(verbose_name='Address number')),
                ('postcode', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)])),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_mitron.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
