# Generated by Django 3.1 on 2020-08-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_mitron', '0003_addressitem_coiiitem_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='procedure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_mitron.procedure'),
            preserve_default=False,
        ),
    ]
